/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces/index'
import { Route as WorkspacesWorkspaceIdRouteRouteImport } from './routes/workspaces/$workspaceId/route'
import { Route as WorkspacesWorkspaceIdIndexRouteImport } from './routes/workspaces/$workspaceId/index'
import { Route as WorkspacesWorkspaceIdUsageRouteImport } from './routes/workspaces/$workspaceId/usage'
import { Route as WorkspacesWorkspaceIdSettingsRouteImport } from './routes/workspaces/$workspaceId/settings'
import { Route as WorkspacesWorkspaceIdKnowledgeRouteImport } from './routes/workspaces/$workspaceId/knowledge'
import { Route as WorkspacesWorkspaceIdActionsRouteImport } from './routes/workspaces/$workspaceId/actions'
import { Route as WorkspacesWorkspaceIdChatsRouteRouteImport } from './routes/workspaces/$workspaceId/chats/route'
import { Route as WorkspacesWorkspaceIdChatsIndexRouteImport } from './routes/workspaces/$workspaceId/chats/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdRouteRoute =
  WorkspacesWorkspaceIdRouteRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspacesWorkspaceIdIndexRoute =
  WorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspacesWorkspaceIdRouteRoute,
  } as any)
const WorkspacesWorkspaceIdUsageRoute =
  WorkspacesWorkspaceIdUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => WorkspacesWorkspaceIdRouteRoute,
  } as any)
const WorkspacesWorkspaceIdSettingsRoute =
  WorkspacesWorkspaceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => WorkspacesWorkspaceIdRouteRoute,
  } as any)
const WorkspacesWorkspaceIdKnowledgeRoute =
  WorkspacesWorkspaceIdKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => WorkspacesWorkspaceIdRouteRoute,
  } as any)
const WorkspacesWorkspaceIdActionsRoute =
  WorkspacesWorkspaceIdActionsRouteImport.update({
    id: '/actions',
    path: '/actions',
    getParentRoute: () => WorkspacesWorkspaceIdRouteRoute,
  } as any)
const WorkspacesWorkspaceIdChatsRouteRoute =
  WorkspacesWorkspaceIdChatsRouteRouteImport.update({
    id: '/chats',
    path: '/chats',
    getParentRoute: () => WorkspacesWorkspaceIdRouteRoute,
  } as any)
const WorkspacesWorkspaceIdChatsIndexRoute =
  WorkspacesWorkspaceIdChatsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspacesWorkspaceIdChatsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRouteRouteWithChildren
  '/workspaces': typeof WorkspacesIndexRoute
  '/workspaces/$workspaceId/chats': typeof WorkspacesWorkspaceIdChatsRouteRouteWithChildren
  '/workspaces/$workspaceId/actions': typeof WorkspacesWorkspaceIdActionsRoute
  '/workspaces/$workspaceId/knowledge': typeof WorkspacesWorkspaceIdKnowledgeRoute
  '/workspaces/$workspaceId/settings': typeof WorkspacesWorkspaceIdSettingsRoute
  '/workspaces/$workspaceId/usage': typeof WorkspacesWorkspaceIdUsageRoute
  '/workspaces/$workspaceId/': typeof WorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/chats/': typeof WorkspacesWorkspaceIdChatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/workspaces': typeof WorkspacesIndexRoute
  '/workspaces/$workspaceId/actions': typeof WorkspacesWorkspaceIdActionsRoute
  '/workspaces/$workspaceId/knowledge': typeof WorkspacesWorkspaceIdKnowledgeRoute
  '/workspaces/$workspaceId/settings': typeof WorkspacesWorkspaceIdSettingsRoute
  '/workspaces/$workspaceId/usage': typeof WorkspacesWorkspaceIdUsageRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/chats': typeof WorkspacesWorkspaceIdChatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRouteRouteWithChildren
  '/workspaces/': typeof WorkspacesIndexRoute
  '/workspaces/$workspaceId/chats': typeof WorkspacesWorkspaceIdChatsRouteRouteWithChildren
  '/workspaces/$workspaceId/actions': typeof WorkspacesWorkspaceIdActionsRoute
  '/workspaces/$workspaceId/knowledge': typeof WorkspacesWorkspaceIdKnowledgeRoute
  '/workspaces/$workspaceId/settings': typeof WorkspacesWorkspaceIdSettingsRoute
  '/workspaces/$workspaceId/usage': typeof WorkspacesWorkspaceIdUsageRoute
  '/workspaces/$workspaceId/': typeof WorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/chats/': typeof WorkspacesWorkspaceIdChatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/workspaces/$workspaceId'
    | '/workspaces'
    | '/workspaces/$workspaceId/chats'
    | '/workspaces/$workspaceId/actions'
    | '/workspaces/$workspaceId/knowledge'
    | '/workspaces/$workspaceId/settings'
    | '/workspaces/$workspaceId/usage'
    | '/workspaces/$workspaceId/'
    | '/workspaces/$workspaceId/chats/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/workspaces'
    | '/workspaces/$workspaceId/actions'
    | '/workspaces/$workspaceId/knowledge'
    | '/workspaces/$workspaceId/settings'
    | '/workspaces/$workspaceId/usage'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/chats'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/workspaces/$workspaceId'
    | '/workspaces/'
    | '/workspaces/$workspaceId/chats'
    | '/workspaces/$workspaceId/actions'
    | '/workspaces/$workspaceId/knowledge'
    | '/workspaces/$workspaceId/settings'
    | '/workspaces/$workspaceId/usage'
    | '/workspaces/$workspaceId/'
    | '/workspaces/$workspaceId/chats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  WorkspacesWorkspaceIdRouteRoute: typeof WorkspacesWorkspaceIdRouteRouteWithChildren
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId': {
      id: '/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId/': {
      id: '/workspaces/$workspaceId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof WorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRouteRoute
    }
    '/workspaces/$workspaceId/usage': {
      id: '/workspaces/$workspaceId/usage'
      path: '/usage'
      fullPath: '/workspaces/$workspaceId/usage'
      preLoaderRoute: typeof WorkspacesWorkspaceIdUsageRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRouteRoute
    }
    '/workspaces/$workspaceId/settings': {
      id: '/workspaces/$workspaceId/settings'
      path: '/settings'
      fullPath: '/workspaces/$workspaceId/settings'
      preLoaderRoute: typeof WorkspacesWorkspaceIdSettingsRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRouteRoute
    }
    '/workspaces/$workspaceId/knowledge': {
      id: '/workspaces/$workspaceId/knowledge'
      path: '/knowledge'
      fullPath: '/workspaces/$workspaceId/knowledge'
      preLoaderRoute: typeof WorkspacesWorkspaceIdKnowledgeRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRouteRoute
    }
    '/workspaces/$workspaceId/actions': {
      id: '/workspaces/$workspaceId/actions'
      path: '/actions'
      fullPath: '/workspaces/$workspaceId/actions'
      preLoaderRoute: typeof WorkspacesWorkspaceIdActionsRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRouteRoute
    }
    '/workspaces/$workspaceId/chats': {
      id: '/workspaces/$workspaceId/chats'
      path: '/chats'
      fullPath: '/workspaces/$workspaceId/chats'
      preLoaderRoute: typeof WorkspacesWorkspaceIdChatsRouteRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRouteRoute
    }
    '/workspaces/$workspaceId/chats/': {
      id: '/workspaces/$workspaceId/chats/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/chats/'
      preLoaderRoute: typeof WorkspacesWorkspaceIdChatsIndexRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdChatsRouteRoute
    }
  }
}

interface WorkspacesWorkspaceIdChatsRouteRouteChildren {
  WorkspacesWorkspaceIdChatsIndexRoute: typeof WorkspacesWorkspaceIdChatsIndexRoute
}

const WorkspacesWorkspaceIdChatsRouteRouteChildren: WorkspacesWorkspaceIdChatsRouteRouteChildren =
  {
    WorkspacesWorkspaceIdChatsIndexRoute: WorkspacesWorkspaceIdChatsIndexRoute,
  }

const WorkspacesWorkspaceIdChatsRouteRouteWithChildren =
  WorkspacesWorkspaceIdChatsRouteRoute._addFileChildren(
    WorkspacesWorkspaceIdChatsRouteRouteChildren,
  )

interface WorkspacesWorkspaceIdRouteRouteChildren {
  WorkspacesWorkspaceIdChatsRouteRoute: typeof WorkspacesWorkspaceIdChatsRouteRouteWithChildren
  WorkspacesWorkspaceIdActionsRoute: typeof WorkspacesWorkspaceIdActionsRoute
  WorkspacesWorkspaceIdKnowledgeRoute: typeof WorkspacesWorkspaceIdKnowledgeRoute
  WorkspacesWorkspaceIdSettingsRoute: typeof WorkspacesWorkspaceIdSettingsRoute
  WorkspacesWorkspaceIdUsageRoute: typeof WorkspacesWorkspaceIdUsageRoute
  WorkspacesWorkspaceIdIndexRoute: typeof WorkspacesWorkspaceIdIndexRoute
}

const WorkspacesWorkspaceIdRouteRouteChildren: WorkspacesWorkspaceIdRouteRouteChildren =
  {
    WorkspacesWorkspaceIdChatsRouteRoute:
      WorkspacesWorkspaceIdChatsRouteRouteWithChildren,
    WorkspacesWorkspaceIdActionsRoute: WorkspacesWorkspaceIdActionsRoute,
    WorkspacesWorkspaceIdKnowledgeRoute: WorkspacesWorkspaceIdKnowledgeRoute,
    WorkspacesWorkspaceIdSettingsRoute: WorkspacesWorkspaceIdSettingsRoute,
    WorkspacesWorkspaceIdUsageRoute: WorkspacesWorkspaceIdUsageRoute,
    WorkspacesWorkspaceIdIndexRoute: WorkspacesWorkspaceIdIndexRoute,
  }

const WorkspacesWorkspaceIdRouteRouteWithChildren =
  WorkspacesWorkspaceIdRouteRoute._addFileChildren(
    WorkspacesWorkspaceIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  WorkspacesWorkspaceIdRouteRoute: WorkspacesWorkspaceIdRouteRouteWithChildren,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
